#!/bin/sh

# teach SQM to re-enable itself when an interface re-appears
#echo "${IFACE} does currently not exist, not even trying starting SQM on nothing." > /dev/kmsg
#logger -t SQM -s "hotplug on interface: ${DEVICE} action: ${ACTION}"

[ "$ACTION" = ifup ] && /etc/init.d/sqm enabled && /usr/lib/sqm/run.sh start ${DEVICE}

