#!/bin/sh

DEV=br-lan
IP4ADDR=122.22.22.22
MACADDR=A:BB:CC:DD:EE:FF

TEMPF=/tmp/dnsupdate.$$

# Parse the above
action=$1
shift

while [ $# -gt 0 ]
do
T=$1
shift
case $T in
	iface:) DEV=$1; shift ;;
	ip4addr:) IP4ADDR=$1; shift;;
	mac:) MACADDR=$1; shift;;
	host:) HOST=$1; shift;;
	domain:) DOMAIN=$1; shift;;
esac
done

REVDOMAIN=what # ??

echo DEV=$DEV IP4ADDR=$IP4ADDR HOST=$HOST MAC=$MACADDR DOMAIN=$DOMAIN >> /tmp/dhcp.log
	echo server ns.$DOMAIN > $TEMPF

naddr=0
#do this when we can figure out prefixes
#ip -6 addr show dev br-lan | grep inet6 | grep -v fe80 | awk '{ print $2 }' | while read ip
echo 2001:470:8717::1/64 | while read ip
do
	IPV6ADDR=`echo $ip | cut -f1 -d/`
	IPV6MASK=`echo $ip | cut -f2 -d/`
	# figure out the PREFIX from all the above somehow
	case $IPV6MASK in
		64) ;;
		48) ;;
	esac
	# IPV6PREFIX=calculate somehow
	IPV6PREFIX=2001:470:8717:
	CIPV6ADDR=$IPV6PREFIX:`ipv6calc --in mac --out eui64 --action geneui64 $MACADDR`
	# construct address
	echo $CIPV6ADDR >> /tmp/dhcp.log
	c=`ping6 -q -c 1 $CIPV6ADDR | grep received | tail -1 | awk '{ print $4}'`
	if [ $c -gt 0 ]
	then
	naddr=`expr $naddr + 1`
	# do the dyndns update somehow
	echo $CIPV6ADDR exists >> /tmp/dhcp.log
	REVADDR=`ipv6calc --in ipv6addr $CIPV6ADDR --out bitstring`  # might be useful to have /prefix
	LEASETIME=86400 # GET THIS SOMEHOW
# will need to be saner for multiple AAAA, can't delete all
	echo zone $DOMAIN >> $TEMPF
	if [ $naddr == 1 ]
	then
	echo update delete $HOST.$DOMAIN AAAA >> $TEMPF
	fi
	echo update add $HOST.$DOMAIN. $LEASETIME AAAA $CIPV6ADDR >> $TEMPF
	# echo zone $REVDOMAIN >> $TEMPF
	# echo update delete the ptr record
	# echo update add the ptr record
	else
	echo $CIPV6ADDR does not exist >> /tmp/dhcp.log
	fi
done

echo send >> $TEMPF

if [ $naddr -gt 0 ]
then
nsupdate -R /dev/urandom -l $TEMPF
fi

# rm $TEMPF
