#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=50

BIN=lighttpd
DEFAULT=/etc/default/cerowrt
LOG_D=/var/log/cerowrt
RUN_D=/var/run
PID_F=$RUN_D/cerowrt.pid
OPTIONS="-f /etc/lighttpd/cerowrt.conf"

start() {
	[ -f $DEFAULT ] && . $DEFAULT
	mkdir -p $LOG_D
	mkdir -p $RUN_D
	$BIN $OPTIONS
}

stop() {
	[ -f $PID_F ] && kill $(cat $PID_F)
}

